#!/bin/bash

function on_ctrl_c {
    # Sometimes, the terminal get into a bad state.
    reset
}

trap on_ctrl_c INT
trap on_ctrl_c TERM

set -e

echo "==> Cleaning dune..."
dune clean

echo "==> Building dune..."
dune build

echo "==> Clearing prior dist..."
rm -f ./public/*.bc.js

echo "==> Creating new dist..."
cp -v -f _build/default/src/*.bc.js ./public

exec foreman start -f Procfile.dev
